### ISSUE TITLE
请问下  zabbix监控mysql的模板没有看到在哪里啊 

### ISSUE THREAD

**Issue by weiyanwei412** [Neeky/mysqltools#1]

**Comment by Neeky** [comment]
你好！ 刚看到你提的issue ；
不太清楚你所指的模板是不是zabbix中的template、如果指的是zabbix中的template那么它还总结&提炼中、大概这个月会发出来。

如果你是要用mysqltools 来实现监控、它目前已经完成了100+的监控项、应该是可以满足大多数需求的了。

可以通过如下方式导出zabbix-agent对mysql进行监控的配置模板

cd mysqltools/mysqltoolspy/
python3 monitor.py export > /tmp/zabbix_agent.conf

**Comment by weiyanwei412** [comment]
谢谢您的回复，我就是说的zabbix模板，template

**Comment by weiyanwei412** [comment]
方便留个联系方式吗，有时间交流下

**Comment by Neeky** [comment]
你好！ 等下我会把联系方式放到readme的最后面。

**Comment by Neeky** [comment]
你好！ 已经更新了、今天还更新了multi source replication 环境的自动化安装配置。

**Comment by weiyanwei412** [comment]
好的谢谢

**Comment by Neeky** [comment]
Hi weiyanwei

我已经增加了zabbix监控mysql的模板文件 mysqltools/deploy/ansible/zabbix/template/zbx_export_mysql_basic_templates.xml 这个模板还在持续更新中

2018-07-02
