### ISSUE TITLE
如何在后继增加新主机？

### ISSUE THREAD

**Issue by dindom999** [Neeky/mysqltools#3]
有个场景不知道怎么处理：
已经安装：
- MasterServer1
- SlaveServer2
- SlaveServer3

现经使用一段时间后，如果要增加SlaveServer4，应该怎么处理？

**Comment by Neeky** [comment]
这个目前处理不了，你只能手工来完成

**Comment by Neeky** [comment]
不过我的下一个项目会解决这个问题，并且会加上 Web 界面。https://github.com/Neeky/dbm-agent
