### ISSUE TITLE
部署单机mysql时报 python2 bindings for rpm are needed for this module

### ISSUE THREAD

**Issue by dbhelp** [Neeky/mysqltools#5]
在部署单机mysql时，报错如下
ansible-playbook install_single_mysql.yaml 
......
TASK [install libaio-devel] *****************************************************************************************************************************************************************
fatal: [host_10_x_x_114]: FAILED! => {"changed": false, "failed": true, "msg": "python2 bindings for rpm are needed for this module. python2 yum module is needed for this  module"}
        to retry, use: --limit @/usr/local/mysqltools/deploy/ansible/mysql/install_single_mysql.retry

**Comment by Neeky** [comment]
mysqltools 不兼容 python-2.x ，可使用 mysqltools 自带的 python3 安装包。

**Comment by dbhelp** [comment]
> mysqltools 不兼容 python-2.x ，可使用 mysqltools 自带的 python3 安装包。

谢谢，我采用这种办法解决了
 ansible-playbook -C install_single_mysql.yaml  -e "ansible_python_interpreter=/usr/bin/python2.7"
